<?php

?>

<h1>
    <?php if ($tooLate): ?>
        <img src="img/exclamation.png" alt="" title="ATRASADA!" />
    <?php endif; ?>
    <?php echo Utils::escape($noticia->getTitle()); ?>
</h1>

<table class="detail">
    <tr>
        <th>Prioridade</th>
        <td><img src="img/priority/<?php echo $noticia->getPriority(); ?>.png" alt="Priority <?php echo $noticia->getPriority(); ?>" title="Priority <?php echo $noticia->getPriority(); ?>" /></td>
    </tr>
    <tr>
        <th>Criada em</th>
        <td><?php echo Utils::escape(Utils::formatDateTime($noticia->getCreatedOn())); ?></td>
    </tr>
    <tr>
        <th>Programada para</th>
        <td>
            <?php if ($tooLate): ?><span class="too-late"><?php endif; ?>
            <?php echo Utils::escape(Utils::formatDateTime($noticia->getDueOn())); ?>
            <?php if ($tooLate): ?></span><?php endif; ?>
        </td>
    </tr>
    <tr>
        <th>Modificada em</th>
        <td><?php echo Utils::escape(Utils::formatDateTime($noticia->getLastModifiedOn())); ?></td>
    </tr>
    <tr>
        <th>Texto</th>
        <td><?php echo Utils::escape($noticia->getDescription()); ?></td>
    </tr>
    <tr>
        <th>Comentário do Autor</th>
        <td><?php echo Utils::escape($noticia->getComment()); ?></td>
    </tr>
    <tr>
        <th>Status</th>
        <td><img src="img/status/<?php echo $noticia->getStatus(); ?>.png" alt="" title="<?php echo Utils::capitalize($noticia->getStatus()); ?>" class="icon" /></td>
    </tr>
    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>
    <tr>
        <th></th>
        <td>
            <div class="statuses">
            <?php foreach (Noticia::allStatuses() as $status): ?>
                <?php if ($status != $noticia->getStatus()): ?>
                    <a href="<?php echo Utils::createLink('change-status', array('id' => $noticia->getId(), 'status' => $status)); ?>" title="NOTICIA alterada para o status <?php echo Utils::capitalize($status); ?>." class="change-status-link"
                       ><img src="img/status/<?php echo $status; ?>.png" alt="" title="Make it <?php echo Utils::capitalize($status); ?>." class="icon" /></a>
                <?php else: ?>
                    <img src="img/status/<?php echo $status; ?>-disabled.png" alt="" title="This NOTICIA is already <?php echo Utils::capitalize($status); ?>." class="icon" />
                <?php endif; ?>
            <?php endforeach; ?>
            </div>
            <div class="actions">
                <a href="<?php echo Utils::createLink('add-edit', array('id' => $noticia->getId())); ?>"><img src="img/action/edit.png" alt="" title="Edit it." class="icon" /></a>
                <a href="<?php echo Utils::createLink('delete', array('id' => $noticia->getId())); ?>" id="delete-link"><img src="img/action/delete.png" alt="" title="Delete it." class="icon" /></a>
            </div>
        </td>
    </tr>
</table>

<p>
    <?php $backLink = Utils::createLink('list', array('status' => $noticia->getStatus())); ?>
    <a href="<?php echo $backLink; ?>"><img src="img/action/back.png" alt="" title="Back to the list." class="icon"/></a>&nbsp;
    <a href="<?php echo $backLink; ?>">Voltar para lista</a>
</p>

<div id="delete-dialog" title="Deseja excluir a NOTICIA?">
    <p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>A NOTICIA será deletada. Você tem certeza?</p>
</div>
<div id="change-status-dialog">
    <form id="change-status-form" method="post">
        <fieldset>
            <div class="field">
                <label>Comentário:</label>
                <textarea name="comment" cols="1" rows="1"></textarea>
            </div>
        </fieldset>
    </form>
</div>
